# Generated by Django 3.0.7 on 2024-01-28 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('feedapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='like',
            field=models.ManyToManyField(related_name='liked_cmnts', to='login.User'),
        ),
        migrations.AlterField(
            model_name='message',
            name='like',
            field=models.ManyToManyField(related_name='liked_msgs', to='login.User'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='login.User'),
        ),
    ]
